### ISSUE TITLE
Some minor enhancement ideas

### ISSUE THREAD

**Issue by GeorgScheumann** [themagicalmammal/howtodebuntu#25]
Hi,

I 've skimmed over your Guide again. So far great job adding new things and fixing other errors. While browsing through I still found some small things that irked me. I will just write these together since I am too lazy to open multiple issues, now a few suggestions:

In https://github.com/themagicalmammal/howtodebuntu#4-signal you recommend the signal Xenial PPA. This was irritating for me, since A) Xenial is out of support in 4 days and B) installing applications not build for your distribution can cause some major dependency conflicts. However after looking it up, this seems to be signals fault, not providing more builds. So I would suggest to link the flatpak there, as you did with other apps. 

In https://github.com/themagicalmammal/howtodebuntu#3-bash-alias you miss some stuff. One minor quirk is the in unneeded sudo in both apt list and apt policy remove that please. Also for apt list I wondered why you use grep since apt list can list without it. It even supports GLOB-Patterns (*appname*). Also you say it's for searching apps, why not apt search?   
Also in alias `d="__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia"`you forgot `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json`. That line also exports your vulkan icd loader. This is needed for some games, because if they can't detect it, they use the first one in the alphabetical order. Usually AMD, so you can't play some games with vulkan, if you don't export the icd-loader too. 

And another note, maybe use a separate file for for aliases like $HOME/.bash_alias since you can do a lot of other stuff with the bashrc so not mixing them up together is imho a good idea. To do this you need to create the .bash_alias file and the add this to the .bashrc: `if [ -f ~/.bash_alias ]; then
        . ~/.bash_alias
fi`
. But even if you don't do that you a missing `source ~/.bashrc ` as an update command for the bashrc there.
So I guess this is about it ;) Have a nice day.

**Comment by themagicalmammal** [comment]
Actually I will soon convert everything into Gists and other parts and move everything to a much more organized way. I am not getting enough time due to my project but I sure will fix each and every fix that you have stated.

Thanks for your suggestions.

**Comment by themagicalmammal** [comment]
fc113b5c72a692c866b09914ca92e54a2a805ef0

**Comment by themagicalmammal** [comment]
Thanks to all your suggestions all amazing like always. I have made the changes.

**Comment by GeorgScheumann** [comment]
Many thanks ;)

You seem to have missed
`source ~/.bashrc`
that is needed so the bashrc gets re read and the apply the changes. Log in and of, would be another way to do it. Or maybe this isn't needed any more and I just missed it.
